

[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

[dependencies]


[[bin]]
name = "Grace"
path = "src/Grace.rs"


[[bin]]
name = "Colleen"
path = "src/Colleen.rs"

[[bin]]
name = "sully"
path = "src/Sully.rs"