Colleen:
	rustc src/Colleen.rs

Grace:
	cargo run --bin Grace

Sully:
	cargo run --bin sully

wipe:
	cargo clean
	rm Grace_kid.rs
	rm Colleen
	rm Sully*
	@echo "\033[1;31m======== sully removed ========\033[0m"

.PHONY: Colleen Grace Sully wipe

